### ISSUE TITLE
Xcode error when using "BonMot" pod and "Swiftilities" in one project

### ISSUE THREAD

**Issue by kirill-ushkov** [Rightpoint/Swiftilities#121]
When using pod "BonMot" and "Swifitilities" in same project, getting error "Ambiguous use of 'tintedImage(color:)'". This is occurring when trying to update to version 0.0.13.

**Comment by ZevEisenberg** [comment]
Yup. This is annoying, and I don't know of any way to resolve it in Swift. The best way forward would be to change the name of the method in Swiftilities, since it's easier to make breaking changes here than in BonMot.

**Comment by chrisballinger** [comment]
I think this is the underlying Swift issue: https://bugs.swift.org/browse/SR-3908

**Comment by chrisballinger** [comment]
FWIW this is how Alamofire solved a similar issue, by prefixing their public extensions: https://github.com/Alamofire/Alamofire/pull/2758
